# Usar a imagem oficial do Python na versão 3.11.5 como base
FROM python:3.11.5-slim

# Definir o diretório de trabalho no container
WORKDIR /app

# Instalar Poetry para gerenciamento de dependências
RUN pip install poetry

# Copiar o arquivo de dependências do Poetry para o container
COPY pyproject.toml poetry.lock* /app/

# Instalar as dependências do projeto usando Poetry
# --no-root: instala as dependências sem instalar o pacote atual
# --no-dev: pula a instalação de pacotes listados na seção [tool.poetry.dev-dependencies]
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-dev

# Instalar Java OpenJDK versão 17
RUN apt-get update \
    && apt-get install -y openjdk-17-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copiar o resto dos arquivos da aplicação para o diretório de trabalho
COPY . /app

# Expor a porta em que o streamlit roda por padrão
EXPOSE 8501

# Comando para executar a aplicação
CMD ["poetry", "run", "streamlit", "run", "app.py"]
